#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 14 15:32:09 2019

@author: nico
"""


import matplotlib.pyplot as plt
import numpy as np


N  = 1000
fs = 1000
Df = fs / N
f  = 1
a  = 1
w  = 2 * np.pi * f
tita  =  0

def seno (a,f, tita, N, fs) :
    w  = 2 * np.pi * f
    t = np.arange(0, (N - 1)/fs, 1 / fs )
    y = a  * np.sin(w * t + tita)
    return [t,y]

t, y = seno (a, f, tita, N, fs)
plt.figure("Funcion  sin(2pi*f*t + tita)")
plt.plot(t,y,color='blue',label='sin(wt)')
plt.xlabel('tiempo normalizado')
plt.ylabel('amplitud ')
plt.axhline(0, color="black")
plt.axvline(0, color="black")
plt.grid()
plt.title('Funcion  sin(2pi*f*t + tita)')
plt.ion()
plt.savefig("funciones.eps")
plt.legend(loc=1)